### PR TITLE
Added CqlBuilder to export

### PR DESCRIPTION
**Pull request by xdmytrox**

### CODE REVIEW

**Comment by kyungmi** [comment]
@DrachovDmytro 
I think it would be good to expand this builder's functionalities.
Could you tell me what would you really do with using directly `CqlBuilder`?

**Comment by xdmytrox** [comment]
Hey @kyungmi.
First of all my apologize that I have not describe that previously.

So the main idea is to force dev to use CqlBuilder for query building.
Imagine next CRUD repository:
```
class CRUDRepo {
   constructor(cassandraDriver) {
      this.driver = cassandraDriver;
   }
   
   create(queryObject) {
      if(!(queryObject instanceof CqlBuilder)) throw TypeError('queryObject should be constructed by cql-builder');
      const { query, params  } = query.build();
      return this.driver.execute(query, params);
   }
   read() {}
   update() {}
   delete() {}
}
```


I don't like approach like

```
create (query, params) {
  ...
}

const { query, params } = cqlBuilder.Insert().......build();
create(query, params);
```

**Comment by kyungmi** [comment]
Thank you for explaining it :)
I will let you know after it is published.

**Comment by kyungmi** [comment]
It was published as v1.0.3. 🙂

**Pull request merged**
